version : '3.2'

services:
  postgres:
    image: 'postgres:10'
    environment:
      - POSTGRES_USER=poker
      - POSTGRES_PASSWORD=poker
      - POSTGRES_DB=poker
  cronapi:
    depends_on: 
      - postgres
    image: 'cb/poker'
    ports:
      - "8000:8000"
    env_file: 
      - '.env'
